name: Allegro.CosmosDb.ConsistencyLevelUtilities Publish

on:
  push:
    tags:
      - 'Allegro.CosmosDb.ConsistencyLevelUtilities_*'

jobs:
  publish:
    uses: ./.github/workflows/template.yml
    with:
      projectName: Allegro.CosmosDb.ConsistencyLevelUtilities
      publish: true
      tagName: ${{ github.ref_name }}
    secrets:
      nugetCertificate: ${{ secrets.NUGET_PRIVATE_KEY_P12 }}
      nugetCertificatePassword: ${{ secrets.GPG_PRIVATE_KEY_PASSWORD }}
      nugetApiKey: ${{ secrets.NUGET_API_KEY }}
